version: '3.1'
services:
  stats-server:
    build: ewm-stat/stat-server
    image: ewm-stat
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:10.2-alpine
    container_name: ewm_stat_db
    ports:
      - "9091:5432"
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
