CREATE TABLE IF NOT EXISTS HITS (
    ID BIGINT generated by default as identity primary key,
    URI VARCHAR(256) not null,
    APP VARCHAR(64) not null,
    IP VARCHAR(32) not null,
    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE not null
);